ci: add checksum check for vulkan SDK download (#184)
This PR adds a checksum check on linux workflows to check Vulkan SDK's
integrity.

---------

Signed-off-by: Nathan Gauër <brioche@google.com>

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -28,6 +28,10 @@ jobs:
       - name: Setup Vulkan SDK
         run: |
           wget -q https://sdk.lunarg.com/sdk/download/1.3.216.0/linux/vulkansdk-linux-x86_64-1.3.216.0.tar.gz
+          if ! echo "2cb10cb94ac656e9e454f1f5ae48e8a833253af5fe22562d27310db45b579212 vulkansdk-linux-x86_64-1.3.216.0.tar.gz" | sha256sum -c --status; then
+            echo "Invalid SHA256 for VulkanSDK's binary. Aborting."
+            exit 1
+          fi
           mkdir "${HOME}/vulkan-sdk"
           tar -xf vulkansdk-linux-x86_64-1.3.216.0.tar.gz -C "${HOME}/vulkan-sdk"
           echo "VULKAN_SDK=${HOME}/vulkan-sdk/1.3.216.0/x86_64" >> $GITHUB_ENV
